application: elreybelmonti
version: 5
runtime: php
api_version: 1
default_expiration: "1d"

handlers:
- url: /qr
  script: qr.html
- url: /resume
  mime_type: application/pdf
  static_files: data/resume.pdf
  upload: data/resume.pdf
- url: /vcard
  mime_type: text/vcard
  static_files: data/vcard.vcf
  upload: data/vcard.vcf
- url: /old
  script: wowtooold.html

- url: /favicon.ico
  mime_type: image/x-icon
  static_files: favicon.ico
  upload: favicon.ico
  expiration: "365d"

- url: /font
  static_dir: font
  application_readable: true
  expiration: "365d"
- url: /css
  static_dir: css
  application_readable: true
- url: /img
  static_dir: img
  application_readable: true
  expiration: "7d"
- url: /data
  static_dir: data
  application_readable: true
- url: /js
  static_dir: js
  application_readable: true
- url: /model
  static_dir: model
  application_readable: true
- url: /dev
  script: index.php
- url: /.*
  static_files: index.html
  upload: index.html
  http_headers:
    Content-language: en
    Content-type: text/html; charset=utf-8
    Cache-Control: max-age=604800, must-revalidate
    X-UA-Compatible: IE=edge,chrome=1
