application: elreybelmonti
version: 6
runtime: php
api_version: 1
default_expiration: "7d"

handlers:

- url: /favicon.ico
  mime_type: image/x-icon
  static_files: favicon.ico
  upload: favicon.ico
  expiration: "365d"

# static content folders
- url: /font
  static_dir: font
  application_readable: true
  expiration: "365d"
- url: /css
  static_dir: css
  application_readable: true
- url: /img
  static_dir: img
  application_readable: true
- url: /data
  static_dir: data
  application_readable: true
- url: /js
  static_dir: js
  application_readable: true
- url: /model
  static_dir: model
  application_readable: true

# dev config, to access the unbuilt version (dev/index.php, dev/qr.html, dev/old.php, dev/about.php)
- url: /dev/model/asyncRequests.json
  script: model/asyncRequests.php
- url: /dev/old
  script: dev/old.php
- url: /dev/about
  script: dev/about.php
- url: /dev
  script: dev/index.php

# mainly for robots.txt, humans.txt and sitemap.xml
- url: /(.*\.(txt|xml))$
  static_files: \1
  upload: .*\.(txt|xml)$

# site's valid pages (/resume, /vcard, /qr, and /old. Everything else loads the main page. /gallery is also a valid path but its routed in JS)
- url: /resume
  mime_type: application/pdf
  static_files: data/resume.pdf
  upload: data/resume.pdf
- url: /vcard
  mime_type: text/vcard
  static_files: data/vcard.vcf
  upload: data/vcard.vcf
- url: /qr
  static_files: qr.html
  upload: qr.html
  http_headers:
    Content-language: en
    Content-type: text/html; charset=utf-8
    Cache-Control: max-age=604800, must-revalidate
    X-UA-Compatible: IE=edge,chrome=1
- url: /old
  static_files: wowtooold.html
  upload: wowtooold.html
  http_headers:
    Content-language: en
    Content-type: text/html; charset=utf-8
    Cache-Control: max-age=604800, must-revalidate
    X-UA-Compatible: IE=edge,chrome=1
- url: /about
  static_files: about.html
  upload: about.html
  http_headers:
    Content-language: en
    Content-type: text/html; charset=utf-8
    Cache-Control: max-age=604800, must-revalidate
    X-UA-Compatible: IE=edge,chrome=1
- url: /.*
  static_files: index.html
  upload: index.html
  http_headers:
    Content-language: en
    Content-type: text/html; charset=utf-8
    Cache-Control: max-age=604800, must-revalidate
    X-UA-Compatible: IE=edge,chrome=1
